name: port-options
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.38
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.140
  - cuda-documentation=12.0.140
  - cuda-driver-dev=11.7.99
  - cuda-gdb=12.0.140
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.140
  - cuda-nsight-compute=12.0.1
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.140
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.146
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.8.86
  - cuda-nvvp=12.0.146
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=12.0.140
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cudatoolkit=11.1.74
  - elfutils=0.189
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.12.1
  - gcc=12.1.0
  - gcc_impl_linux-64=12.1.0
  - gds-tools=1.5.1.14
  - giflib=5.2.1
  - glew=2.1.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=73.2
  - idna=3.4
  - intel-openmp=2022.1.0
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libarchive=3.6.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.10.3.66
  - libcufft=10.9.0.58
  - libcufft-dev=10.7.2.124
  - libcufile=1.5.1.14
  - libcufile-dev=1.5.1.14
  - libcurand=10.3.1.124
  - libcurand-dev=10.3.1.124
  - libcurl=8.2.1
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglu=9.0.0
  - libgomp=13.1.0
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libmicrohttpd=0.9.76
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.8.0.2
  - libpciaccess=0.17
  - libpng=1.6.39
  - libsanitizer=12.1.0
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mesalib=23.1.4
  - mkl=2022.1.0
  - mpi=1.0
  - mpi4py=3.1.4
  - mpich=3.3.2
  - ncurses=6.4
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nsight-compute=2022.4.1.6
  - openh264=2.1.1
  - openssl=3.1.2
  - pip=22.3.1
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.9.17
  - python_abi=3.9
  - pytorch=1.9.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wheel=0.37.1
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-glproto=1.4.17
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxcursor=1.2.0
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-randrproto=1.5.0
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.19.3
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - atari-py==0.2.9
    - cachetools==5.3.0
    - captum==0.6.0
    - cffi==1.15.1
    - charset-normalizer==3.0.1
    - chex==0.1.5
    - click==8.1.7
    - cloudpickle==1.2.2
    - cmake==3.26.4
    - custom-minigrid==0.0.1
    - cycler==0.11.0
    - cython==0.29.36
    - decorator==5.1.1
    - dill==0.3.4
    - dm-tree==0.1.8
    - dopamine-rl==4.0.6
    - einops==0.6.1
    - farama-notifications==0.0.4
    - fasteners==0.18
    - filelock==3.9.0
    - flatbuffers==23.1.21
    - flax==0.4.1
    - future==0.18.3
    - gast==0.4.0
    - gin-config==0.5.0
    - glcontext==2.4.0
    - glfw==1.12.0
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.1
    - gym==0.15.7
    - gym3==0.3.3
    - gymnasium==0.26.3
    - gymnasium-notices==0.0.1
    - h5py==3.8.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.3.0
    - importlib-metadata==6.0.0
    - jax==0.4.2
    - jax-jumpy==1.0.0
    - jaxlib==0.4.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==15.0.6.1
    - lit==16.0.6
    - lockfile==0.12.2
    - markdown==3.4.1
    - markupsafe==2.1.2
    - matplotlib==3.4.3
    - minigrid==2.1.0
    - moderngl==5.8.2
    - mpmath==1.3.0
    - msgpack==1.0.4
    - mujoco-py==2.1.2.14
    - networkx==3.0
    - numpy==1.21.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - optax==0.1.4
    - packaging==23.0
    - pandas==1.5.3
    - pfrl==0.3.0
    - pillow==8.2.0
    - procgen==0.10.7
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygame==2.4.0
    - pyglet==1.5.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-graphviz==0.20.1
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.0
    - scipy==1.7.1
    - seeding==0.1.0
    - six==1.16.0
    - sympy==1.12
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.30.0
    - tensorflow-probability==0.19.0
    - termcolor==2.2.0
    - tf-slim==1.1.0
    - threadpoolctl==3.0.0
    - tifffile==2023.2.2
    - toolz==0.12.0
    - torch==1.9.1
    - torch-ac==1.4.0
    - torch-summary==1.4.5
    - torchvision==0.15.2
    - torchviz==0.0.2
    - tqdm==4.65.0
    - triton==2.0.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.14
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.12.0
